import { initializeApp } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js";
import { getAuth, GoogleAuthProvider, signInWithPopup, onAuthStateChanged, signOut } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js";
import { getFirestore, doc, getDoc, setDoc, collection, addDoc, updateDoc, query, where, orderBy, getDocs, serverTimestamp } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js";

const firebaseConfig={apiKey:"AIzaSyBh7-h4GxX_cYZphqIvIYVVzMjQVFLKQyE",authDomain:"chatgpt-household-attendance.firebaseapp.com",projectId:"chatgpt-household-attendance",storageBucket:"chatgpt-household-attendance.firebasestorage.app",messagingSenderId:"640078047318",appId:"1:640078047318:web:fa508fb29be6621378f3f7"};
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),provider=new GoogleAuthProvider();
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const state={user:null,household:null,workers:[],attendance:[],reports:[],selectedDate:new Date()};
const iso=d=>{const x=new Date(d);return `${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,"0")}-${String(x.getDate()).padStart(2,"0")}`};
const parseDate=s=>{const [y,m,d]=String(s).split("-").map(Number);return new Date(y,m-1,d)};
const esc=s=>String(s??"").replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const normEmail=e=>String(e||"").trim().toLowerCase();
const path=(name,id)=>id?doc(db,"households",state.household.id,name,id):collection(db,"households",state.household.id,name);
const owner=()=>state.household?.ownerUid===state.user?.uid;
const shiftType=w=>w?.shiftType||"double"; // Existing workers without the field remain double-shift; new workers default to single.
function error(t,m){$("#modalContent").innerHTML=`<h2 class="error-title">${esc(t)}</h2><p>${esc(m)}</p><button class="primary-btn" id="ok">OK</button>`;$("#modal").classList.remove("hidden");$("#ok").onclick=()=>$("#modal").classList.add("hidden")}
function toast(m){const t=$("#toast");t.textContent=m;t.classList.remove("hidden");setTimeout(()=>t.classList.add("hidden"),2400)}
async function ensureHousehold(){
  const ownRef=doc(db,"households",state.user.uid),ownSnap=await getDoc(ownRef),email=normEmail(state.user.email);
  if(ownSnap.exists()){
    const household=normalizeHousehold(ownSnap);
    if(!household.memberEmails.includes(email)){household.memberEmails=Array.from(new Set([...(household.memberEmails||[]),email].filter(Boolean)));await setDoc(ownRef,{memberEmails:household.memberEmails,updatedAt:serverTimestamp()},{merge:true})}
    return household;
  }
  if(email){const invited=await getDocs(query(collection(db,"households"),where("memberEmails","array-contains",email)));if(!invited.empty)return normalizeHousehold(invited.docs[0])}
  await setDoc(ownRef,{ownerUid:state.user.uid,ownerEmail:email,name:"My Household",members:[state.user.uid],memberEmails:[email],createdAt:serverTimestamp()});
  return {id:state.user.uid,ownerUid:state.user.uid,ownerEmail:email,members:[state.user.uid],memberEmails:[email],name:"My Household"};
}
function normalizeHousehold(s){const d=s.data();return{id:s.id,...d,members:Array.isArray(d.members)?d.members:[],memberEmails:Array.isArray(d.memberEmails)?d.memberEmails.map(normEmail).filter(Boolean):[normEmail(d.ownerEmail)].filter(Boolean)}}
async function load(){
  $("#loadingView").classList.remove("hidden");$("#mainView").classList.add("hidden");
  try{
    state.household=await ensureHousehold();
    const [w,a,r]=await Promise.all([getDocs(query(path("workers"),orderBy("name"))),getDocs(query(path("attendance"),orderBy("date","desc"))),getDocs(query(path("reports"),orderBy("periodStart","desc"))) ]);
    state.workers=w.docs.map(d=>({id:d.id,...d.data(),shiftType:d.data().shiftType??"double",monthlyPaidLeaves:Number(d.data().monthlyPaidLeaves??2),dailyRate:Number(d.data().dailyRate??0),monthlySalary:Number(d.data().monthlySalary??0)}));
    state.attendance=a.docs.map(d=>({id:d.id,...d.data()}));state.reports=r.docs.map(d=>({id:d.id,...d.data()}));
    await createDueReports();
    if(state.reports.length!==r.size){const rr=await getDocs(query(path("reports"),orderBy("periodStart","desc")));state.reports=rr.docs.map(d=>({id:d.id,...d.data()}))}
    render();$("#loadingView").classList.add("hidden");$("#mainView").classList.remove("hidden");
  }catch(e){$("#loadingView").classList.add("hidden");error("Couldn't load data",e.message||"Please check your connection.")}
}
const att=(wid,date)=>state.attendance.find(x=>x.workerId===wid&&x.date===date);
function shiftValue(wid,date,shift){return att(wid,date)?.[shift]||"unmarked"}
const states=["unmarked","present","absent","leave"];
function nextState(v){return states[(states.indexOf(v)+1)%states.length]||"present"}
async function saveAttendance(wid,date,shift,value){
  const a=att(wid,date);try{if(a)await updateDoc(path("attendance",a.id),{[shift]:value,updatedAt:serverTimestamp()});else await addDoc(path("attendance"),{workerId:wid,date,morning:shift==="morning"?value:"unmarked",evening:shift==="evening"?value:"unmarked",createdAt:serverTimestamp(),updatedAt:serverTimestamp()});await load();toast("Attendance saved")}catch(e){error("Attendance wasn't saved",e.message)}}
async function mark(wid,shift){await saveAttendance(wid,iso(state.selectedDate),shift,nextState(shiftValue(wid,iso(state.selectedDate),shift)))}
const stampGlyph={present:"✓",absent:"✕",leave:"L"};
function shiftButton(w,date,shift){const v=shiftValue(w.id,date,shift);return `<button class="shift-btn ${v}" data-shift="${shift}" data-worker="${w.id}" data-date="${date}"><span class="stamp-mark">${stampGlyph[v]||""}</span><span>${shift[0].toUpperCase()+shift.slice(1)}</span><span class="lbl">${v==="unmarked"?"Tap to mark":v.toUpperCase()}</span></button>`}
function dateControl(){const d=iso(state.selectedDate);return `<div class="date-control"><button class="mini-action" data-date-move="-1">‹</button><label><span class="subtle">Attendance date</span><input id="attendanceDate" type="date" value="${d}"></label><button class="mini-action" data-date-move="1">›</button><button class="mini-action" data-date-today="1">Today</button></div>`}
function renderToday(){const active=state.workers.filter(w=>w.active!==false),d=iso(state.selectedDate),date=parseDate(d).toLocaleDateString(undefined,{weekday:"long",day:"numeric",month:"long",year:"numeric"});$("#todayPanel").innerHTML=`<div class="section-head"><div><h2>Attendance</h2><div class="subtle">${date}</div></div><button class="mini-action" data-action="add">+ Worker</button></div>${dateControl()}${active.length?active.map(w=>`<article class="worker-card"><div><p class="worker-name">${esc(w.name)}</p><div class="worker-meta">${esc(w.role||"Worker")} · ${shiftType(w)==="single"?"1 shift · morning":"2 shifts · morning + evening"} · ${w.monthlyPaidLeaves} paid leave days/month</div></div><button class="mini-action" data-action="edit" data-id="${w.id}">Details</button><div class="shift-row">${shiftButton(w,d,"morning")}${shiftType(w)!=="single"?shiftButton(w,d,"evening"):""}</div></article>`).join(""):"<div class='summary-card'><h3>No workers yet</h3><p class='subtle'>Add your first worker.</p><button class='primary-btn' data-action='add'>Add worker</button></div>"}`}
function workerRows(w,start,end){return state.attendance.filter(a=>a.workerId===w.id&&a.date>=start&&a.date<=end)}
function workerStats(w,start,end){
  const rows=workerRows(w,start,end),single=shiftType(w)==="single";
  const present=rows.reduce((n,a)=>n+(a.morning==="present")+(single?0:a.evening==="present"),0),leave=rows.reduce((n,a)=>n+(a.morning==="leave")+(single?0:a.evening==="leave"),0),absent=rows.reduce((n,a)=>n+(a.morning==="absent")+(single?0:a.evening==="absent"),0);
  const divisor=single?1:2,presentDays=present/divisor,leaveDays=leave/divisor,absentDays=absent/divisor,paidLeaveDays=Math.min(leaveDays,Number(w.monthlyPaidLeaves||0)),unpaidLeaveDays=Math.max(0,leaveDays-paidLeaveDays),days=Math.floor((parseDate(end)-parseDate(start))/86400000)+1;
  const dailyRate=Number(w.dailyRate||0),monthlySalary=Number(w.monthlySalary||0),paymentMethod=w.payType==="monthly"?"monthly":"daily";let basePayment,deduction,finalPayment;
  if(paymentMethod==="monthly"){basePayment=monthlySalary;deduction=w.paymentPolicy==="full"?0:unpaidLeaveDays*(monthlySalary/Math.max(1,days));finalPayment=Math.max(0,basePayment-deduction)}else{basePayment=(presentDays+paidLeaveDays)*dailyRate;deduction=0;finalPayment=Math.max(0,basePayment)}
  return{workerId:w.id,name:w.name,shiftType:shiftType(w),presentShifts:present,leaveShifts:leave,absentShifts:absent,presentDays,leaveDays,absentDays,paidLeaveDays,unpaidLeaveDays,days,dailyRate,monthlySalary,paymentMethod,basePayment,deduction,finalPayment};
}
function monthRows(w,y,m){const days=new Date(y,m+1,0).getDate(),single=shiftType(w)==="single";return Array.from({length:days},(_,i)=>{const date=iso(new Date(y,m,i+1)),a=att(w.id,date),morning=a?.morning||"unmarked",evening=single?"unmarked":(a?.evening||"unmarked");return{date,morning,evening}})}
function renderMonth(){const d=new Date(),y=d.getFullYear(),m=d.getMonth(),days=new Date(y,m+1,0).getDate(),active=state.workers.filter(w=>w.active!==false),start=iso(new Date(y,m,1)),end=iso(new Date(y,m,days));let html=`<div class="section-head"><div><h2>${d.toLocaleDateString(undefined,{month:"long",year:"numeric"})}</h2><div class="subtle">Full month status · attended days are shift-aware</div></div></div>`;html+=active.map(w=>{const s=workerStats(w,start,end);return `<div class="summary-card"><div class="section-head"><h3>${esc(w.name)}</h3></div><div class="stats"><div class="stat"><strong>${s.presentDays}</strong><span>Attended days</span></div><div class="stat"><strong>${s.leaveDays}</strong><span>Leave days</span></div><div class="stat"><strong>${s.absentDays}</strong><span>Absent days</span></div></div></div>`}).join("");html+=`<div class="calendar-wrap"><div class="calendar" style="grid-template-columns:110px repeat(${days},36px)"><div class="day">Worker</div>${Array.from({length:days},(_,i)=>`<div class="day">${i+1}</div>`).join("")}${active.map(w=>`<div class="worker-label">${esc(w.name)}</div>${monthRows(w,y,m).map(x=>{const vals=[x.morning,x.evening],c=vals.includes("present")?"present":vals.includes("leave")?"leave":vals.includes("absent")?"absent":"",symbol=c==="present"?"✓":c==="leave"?"L":c==="absent"?"A":"·";return `<div class="cell ${c}" title="Morning: ${x.morning}; Evening: ${x.evening}">${symbol}</div>`}).join("")}`).join("")}</div><div class="fade-edge"></div></div><p class="scroll-hint">↔ Swipe to see all ${days} days</p>`;$("#monthPanel").innerHTML=html}
function period(kind,anchor=new Date()){const d=new Date(anchor);if(kind==="week"){const s=new Date(d);s.setDate(d.getDate()-d.getDay());const e=new Date(s);e.setDate(s.getDate()+6);return{start:iso(s),end:iso(e),label:`Week ${iso(s)} → ${iso(e)}`}}const s=new Date(d.getFullYear(),d.getMonth(),1),e=new Date(d.getFullYear(),d.getMonth()+1,0);return{start:iso(s),end:iso(e),label:s.toLocaleDateString(undefined,{month:"long",year:"numeric"})}}
function calc(start,end,workers=state.workers){return workers.filter(w=>w.active!==false).map(w=>workerStats(w,start,end))}
async function writeReport(kind,p){await setDoc(path("reports",`${kind}_${p.start}`),{kind,periodStart:p.start,periodEnd:p.end,label:p.label,summary:calc(p.start,p.end),generatedAt:serverTimestamp(),autoGenerated:true},{merge:true})}
async function createDueReports(){const now=new Date(),previousDay=new Date(now);previousDay.setDate(now.getDate()-1);const completedWeek=previousDay.getDay()===6?period("week",previousDay):null,previousMonth=new Date(now.getFullYear(),now.getMonth()-1,1),monthEnd=new Date(now.getFullYear(),now.getMonth(),0),monthClosed=iso(monthEnd)<iso(now),existing=new Set(state.reports.map(r=>`${r.kind}_${r.periodStart}`));if(completedWeek&&!existing.has(`week_${completedWeek.start}`))await writeReport("week",completedWeek);if(monthClosed){const p=period("month",previousMonth);if(!existing.has(`month_${p.start}`))await writeReport("month",p)}}
function reportCard(r){const total=(r.summary||[]).reduce((n,x)=>n+Number(x.finalPayment||0),0);return `<article class="report-card"><div class="section-head"><div><h3>${esc(r.label)}</h3><div class="subtle">${r.kind==="week"?"Sunday–Saturday":"Full calendar month"}</div></div><strong>₹${total.toLocaleString("en-IN")}</strong></div><div class="report-grid">${(r.summary||[]).map(x=>`<div class="report-metric"><strong>${esc(x.name)}</strong><span>${x.presentDays??0} attended days · ${x.leaveDays??0} leave days · ${x.unpaidLeaveDays??0} unpaid leave days · ₹${Number(x.finalPayment||0).toLocaleString("en-IN")}</span></div>`).join("")}</div></article>`}
function renderReports(){const ws=state.reports.filter(r=>r.kind==="week").slice(0,8),ms=state.reports.filter(r=>r.kind==="month").slice(0,12);$("#reportsPanel").innerHTML=`<div class="section-head"><div><h2>Reports</h2><div class="subtle">Reports are created when a period closes.</div></div></div><div class="report-actions"><button class="mini-action" data-action="report" data-kind="week">Generate current week</button><button class="mini-action" data-action="report" data-kind="month">Generate current month</button></div><h3>Weekly</h3>${ws.map(reportCard).join("")||"<div class='report-card'><p class='subtle'>No weekly reports yet.</p></div>"}<h3>Monthly</h3>${ms.map(reportCard).join("")||"<div class='report-card'><p class='subtle'>No monthly reports yet.</p></div>"}`}
function renderWorkers(){$("#workersPanel").innerHTML=`<div class="section-head"><div><h2>Workers</h2><div class="subtle">Each worker can have one or two attendance shifts.</div></div><button class="mini-action" data-action="add">+ Worker</button></div>${state.workers.map(w=>`<article class="worker-card"><div><p class="worker-name">${esc(w.name)} ${w.active===false?"· Inactive":""}</p><div class="worker-meta">${esc(w.role||"Worker")} · ${shiftType(w)==="single"?"Single shift":"Double shift"} · ${w.monthlyPaidLeaves} leave days · ₹${Number(w.dailyRate||0).toLocaleString("en-IN")}/day · ${w.paymentPolicy==="full"?"pay full if leave exceeds allowance":"deduct excess leave"}</div></div><button class="mini-action" data-action="edit" data-id="${w.id}">Edit</button></article>`).join("")}`}
function renderHousehold(){const emails=state.household.memberEmails||[],isOwner=owner();$("#householdPanel").innerHTML=`<div class="section-head"><div><h2>Household users</h2><div class="subtle">Share this household with Google accounts by email.</div></div></div><article class="summary-card"><h3>${esc(state.household.name||"My Household")}</h3><p class="subtle">Owner: ${esc(state.household.ownerEmail||"")}</p>${isOwner?`<form id="memberForm" class="member-form"><label><span class="subtle">Invite Google account email</span><input name="email" type="email" required placeholder="name@example.com"></label><button class="primary-btn">Add member</button></form>`:`<p class="subtle">Only the owner can add or remove household members.</p>`}</article>${emails.map(email=>`<article class="member-card"><div><strong>${esc(email)}</strong><div class="subtle">${email===normEmail(state.household.ownerEmail)?"Owner":"Member"}</div></div>${isOwner&&email!==normEmail(state.household.ownerEmail)?`<button class="mini-action danger-action" data-member-remove="${esc(email)}">Remove</button>`:""}</article>`).join("")}`;const form=$("#memberForm");if(form)form.onsubmit=addMember}
async function addMember(e){e.preventDefault();if(!owner())return error("Only the owner can add members","Ask the household owner to update users.");const email=normEmail(new FormData(e.target).get("email"));if(!email)return;const memberEmails=Array.from(new Set([...(state.household.memberEmails||[]).map(normEmail),email].filter(Boolean)));try{await updateDoc(doc(db,"households",state.household.id),{memberEmails,updatedAt:serverTimestamp()});state.household.memberEmails=memberEmails;render();toast("Member added")}catch(err){error("Member wasn't added",err.message)}}
async function removeMember(email){if(!owner())return;const target=normEmail(email),ownerEmail=normEmail(state.household.ownerEmail),memberEmails=(state.household.memberEmails||[]).map(normEmail).filter(e=>e&&(e!==target||e===ownerEmail));try{await updateDoc(doc(db,"households",state.household.id),{memberEmails,updatedAt:serverTimestamp()});state.household.memberEmails=memberEmails;render();toast("Member removed")}catch(err){error("Member wasn't removed",err.message)}}
function syncAccountUI(){const emailEl=$("#accountEmail");if(emailEl)emailEl.textContent=state.user?.email||"";const avatarEl=$("#avatarInitial");if(avatarEl)avatarEl.textContent=(state.user?.email||"?").trim()[0]?.toUpperCase()||"?"}
// Panel visibility is owned exclusively by navigation.js — render() must never toggle
// panel .hidden classes itself, or it will silently fight the active tab (this was Bug 2).
function render(){renderToday();renderMonth();renderReports();renderWorkers();renderHousehold();syncAccountUI()}
function workerModal(id){const w=id?state.workers.find(x=>x.id===id):null;const currentShift=w?shiftType(w):"single";$("#modalContent").innerHTML=`<h2>${w?"Edit worker":"Add worker"}</h2><p class="subtle">Set this worker's rules. Existing workers without a saved shift setting remain double-shift.</p><form id="wf" class="form-grid"><label>Name<input name="name" required value="${esc(w?.name||"")}"></label><label>Role<input name="role" value="${esc(w?.role||"")}" placeholder="Housemaid, car cleaner…"></label><label>Attendance shifts<select name="shiftType"><option value="single" ${currentShift==="single"?"selected":""}>One shift — morning only</option><option value="double" ${currentShift!=="single"?"selected":""}>Two shifts — morning + evening</option></select></label><label>Paid leave allowance (days/month)<input name="leave" type="number" min="0" step="1" value="${w?.monthlyPaidLeaves??2}"></label><label>Daily rate (₹)<input name="rate" type="number" min="0" step="1" value="${w?.dailyRate??0}"></label><label>Payment method<select name="payType"><option value="daily" ${w?.payType!=="monthly"?"selected":""}>Daily rate</option><option value="monthly" ${w?.payType==="monthly"?"selected":""}>Monthly salary</option></select></label><label>Monthly salary (₹)<input name="salary" type="number" min="0" step="1" value="${w?.monthlySalary??0}"></label><label>If leave allowance is exceeded<select name="policy"><option value="deduct" ${w?.paymentPolicy!=="full"?"selected":""}>Deduct excess leave</option><option value="full" ${w?.paymentPolicy==="full"?"selected":""}>Pay full amount anyway</option></select></label><label>Worker status<select name="active"><option value="true" ${w?.active!==false?"selected":""}>Active</option><option value="false" ${w?.active===false?"selected":""}>Inactive</option></select></label><div class="form-actions"><button type="button" class="secondary-btn" id="cancel">Cancel</button><button class="primary-btn">Save</button></div></form>`;$("#modal").classList.remove("hidden");$("#cancel").onclick=()=>$("#modal").classList.add("hidden");$("#wf").onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),data={name:String(f.get("name")).trim(),role:String(f.get("role")).trim(),shiftType:String(f.get("shiftType")||"single"),monthlyPaidLeaves:Number(f.get("leave")),dailyRate:Number(f.get("rate")),payType:f.get("payType"),monthlySalary:Number(f.get("salary")),paymentPolicy:f.get("policy"),active:f.get("active")==="true",updatedAt:serverTimestamp()};if(!data.name)return;try{if(w)await updateDoc(path("workers",w.id),data);else await addDoc(path("workers"),{...data,createdAt:serverTimestamp()});$("#modal").classList.add("hidden");await load();toast("Worker saved")}catch(err){error("Worker wasn't saved",err.message)}}}
$("#googleSignInBtn").onclick=async()=>{try{await signInWithPopup(auth,provider)}catch(e){error("Google sign-in failed",e.message)}};
$("#refreshBtn").onclick=()=>{closeAccountMenu();load()};$("#closeModal").onclick=()=>$("#modal").classList.add("hidden");
function closeAccountMenu(){const m=$("#accountMenu");if(m){m.classList.add("hidden");$("#accountBtn")?.setAttribute("aria-expanded","false")}}
$("#accountBtn").onclick=e=>{e.stopPropagation();const m=$("#accountMenu"),open=m.classList.contains("hidden");m.classList.toggle("hidden");$("#accountBtn").setAttribute("aria-expanded",String(open))};
document.addEventListener("click",()=>closeAccountMenu());
document.addEventListener("click",e=>{const s=e.target.closest("[data-shift]");if(s){s.classList.add("stamping");void s.offsetWidth;state.selectedDate=parseDate(s.dataset.date);mark(s.dataset.worker,s.dataset.shift);return}const dm=e.target.closest("[data-date-move]");if(dm){state.selectedDate=new Date(state.selectedDate);state.selectedDate.setDate(state.selectedDate.getDate()+Number(dm.dataset.dateMove));renderToday();return}const dt=e.target.closest("[data-date-today]");if(dt){state.selectedDate=new Date();renderToday();return}const rm=e.target.closest("[data-member-remove]");if(rm){removeMember(rm.dataset.memberRemove);return}const a=e.target.closest("[data-action]");if(!a)return;if(a.dataset.action==="add")workerModal();if(a.dataset.action==="edit")workerModal(a.dataset.id);if(a.dataset.action==="report"){const kind=a.dataset.kind||"week";writeReport(kind,period(kind)).then(load).catch(err=>error("Report failed",err.message))}});
document.addEventListener("change",e=>{if(e.target.id==="attendanceDate"){state.selectedDate=parseDate(e.target.value);renderToday()}});document.addEventListener("click",e=>{if(e.target.id==="logoutBtn"){closeAccountMenu();signOut(auth).catch(err=>error("Sign out failed",err.message))}});
onAuthStateChanged(auth,async u=>{state.user=u;syncAccountUI();if(!u){$("#loginView").classList.remove("hidden");$("#loadingView").classList.add("hidden");$("#mainView").classList.add("hidden")}else{$("#loginView").classList.add("hidden");await load()}});
