import { initializeApp } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js";
import { getAuth, GoogleAuthProvider, signInWithPopup, onAuthStateChanged, signOut } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js";
import { getFirestore, doc, getDoc, setDoc, collection, addDoc, updateDoc, query, orderBy, getDocs, serverTimestamp } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js";

const firebaseConfig={apiKey:"AIzaSyBh7-h4GxX_cYZphqIvIYVVzMjQVFLKQyE",authDomain:"chatgpt-household-attendance.firebaseapp.com",projectId:"chatgpt-household-attendance",storageBucket:"chatgpt-household-attendance.firebasestorage.app",messagingSenderId:"640078047318",appId:"1:640078047318:web:fa508fb29be6621378f3f7"};
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),provider=new GoogleAuthProvider();
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={user:null,household:null,workers:[],attendance:[],reports:[],activeView:"today",loading:false,lastLoaded:null};
const iso=d=>{const x=new Date(d);return `${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,"0")}-${String(x.getDate()).padStart(2,"0")}`};
const today=()=>iso(new Date());
const monthKey=d=>{const x=new Date(d);return `${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,"0")}`};
const daysInMonth=(y,m)=>new Date(y,m,0).getDate();
const esc=s=>String(s??"").replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const householdRef=()=>doc(db,"households",state.user.uid);
const workersRef=()=>collection(db,"households",state.user.uid,"workers");
const attendanceRef=()=>collection(db,"households",state.user.uid,"attendance");
const reportsRef=()=>collection(db,"households",state.user.uid,"reports");
function showError(title,message){$("#modalContent").innerHTML=`<h2 class="error-title">${esc(title)}</h2><p>${esc(message)}</p><button class="primary-btn" id="modalOk">OK</button>`;$("#modal").classList.remove("hidden");$("#modalOk").onclick=()=>$("#modal").classList.add("hidden")}
function toast(message){$("#toast").textContent=message;$("#toast").classList.remove("hidden");setTimeout(()=>$("#toast").classList.add("hidden"),2600)}
function setLoading(on){state.loading=on;$("#loadingView").classList.toggle("hidden",!on);if(on)$("#mainView").classList.add("hidden")}
function workerDefaults(w){return {...w,monthlyPaidLeaves:Number(w.monthlyPaidLeaves??2),dailyRate:Number(w.dailyRate??0),paymentPolicy:w.paymentPolicy??"deduct",active:w.active!==false}}
async function ensureHousehold(){const ref=householdRef(),snap=await getDoc(ref);if(!snap.exists()){await setDoc(ref,{ownerUid:state.user.uid,ownerEmail:state.user.email||"",name:"My Household",createdAt:serverTimestamp(),members:[state.user.uid]})}else if(!(snap.data().members||[]).includes(state.user.uid)){await updateDoc(ref,{members:[...(snap.data().members||[]),state.user.uid]})}}
async function loadData(){setLoading(true);try{await ensureHousehold();const [h,ws,as,rs]=await Promise.all([getDoc(householdRef()),getDocs(query(workersRef(),orderBy("name"))),getDocs(query(attendanceRef(),orderBy("date","desc"))),getDocs(query(reportsRef(),orderBy("periodStart","desc")))]);state.household=h.data()||{};state.workers=ws.docs.map(d=>({id:d.id,...workerDefaults(d.data())}));state.attendance=as.docs.map(d=>({id:d.id,...d.data()}));state.reports=rs.docs.map(d=>({id:d.id,...d.data()}));state.lastLoaded=new Date();render();checkDueReports();}catch(e){console.error(e);showError("Couldn't load your data",e.message||"Please check your connection and try again.")}finally{setLoading(false);}}
function attendanceFor(workerId,date){return state.attendance.find(a=>a.workerId===workerId&&a.date===date)}
async function markShift(workerId,shift,status){const date=today(),existing=attendanceFor(workerId,date);const data={workerId,date,[shift]:status,updatedAt:serverTimestamp()};try{if(existing){await updateDoc(doc(db,"households",state.user.uid,"attendance",existing.id),data)}else{await addDoc(attendanceRef(),{workerId,date,morning:"unmarked",evening:"unmarked",...data,createdAt:serverTimestamp()})}await loadData();toast("Attendance saved")}catch(e){showError("Attendance wasn't saved",e.message||"Please try again.")}}
function statusButton(worker,shift){const a=attendanceFor(worker.id,today()),v=a?.[shift]||"unmarked";return `<button class="shift-btn ${v}" data-shift="${shift}" data-worker="${worker.id}">${shift[0].toUpperCase()+shift.slice(1)} · ${v==='present'?'Present':v==='absent'?'Absent':v==='leave'?'Leave':'Mark'}</button>`}
function renderToday(){const p=$("#todayPanel"),date=new Date().toLocaleDateString(undefined,{weekday:"long",day:"numeric",month:"long"});if(!state.workers.length){p.innerHTML=`<div class="section-head"><div><h2>Today</h2><div class="subtle">${date}</div></div></div><div class="summary-card"><h3>No workers yet</h3><p class="subtle">Add your first worker. The app will ask the payment and leave questions before saving them.</p><button class="primary-btn" data-action="add-worker">Add worker</button></div>`;return}p.innerHTML=`<div class="section-head"><div><h2>Today</h2><div class="subtle">${date}</div></div><button class="mini-action" data-action="add-worker">+ Worker</button></div>${state.workers.filter(w=>w.active).map(w=>`<article class="worker-card"><div><p class="worker-name">${esc(w.name)}</p><div class="worker-meta">${esc(w.role||"Worker")} · ${w.monthlyPaidLeaves} paid leave${w.monthlyPaidLeaves===1?'':'s'}</div></div><button class="mini-action" data-action="worker" data-id="${w.id}">Details</button><div class="shift-row">${statusButton(w,"morning")}${statusButton(w,"evening")}</div></article>`).join("")}`}
function monthStats(worker){const mk=monthKey(new Date()),rows=state.attendance.filter(a=>a.workerId===worker.id&&a.date.startsWith(mk));const present=rows.reduce((n,a)=>n+(a.morning==='present'?1:0)+(a.evening==='present'?1:0),0);const absent=rows.reduce((n,a)=>n+(a.morning==='absent'?1:0)+(a.evening==='absent'?1:0),0);const leaves=rows.reduce((n,a)=>n+(a.morning==='leave'?1:0)+(a.evening==='leave'?1:0),0);return {present,absent,leaves,rows}}
function renderMonth(){const p=$("#monthPanel"),now=new Date(),year=now.getFullYear(),month=now.getMonth()+1,days=daysInMonth(year,month),dayNames=["Sun","Mon","Tue","Wed","Thu","Fri","Sat"];p.innerHTML=`<div class="section-head"><div><h2>${now.toLocaleDateString(undefined,{month:"long",year:"numeric"})}</h2><div class="subtle">Attendance overview · scroll horizontally if needed</div></div></div>${state.workers.filter(w=>w.active).map(w=>{const s=monthStats(w);return `<div class="summary-card"><div class="section-head"><div><h3>${esc(w.name)}</h3><div class="subtle">${esc(w.role||"Worker")}</div></div><div class="subtle">${s.present} shifts present</div></div><div class="stats"><div class="stat"><strong>${s.present}</strong><span>Present shifts</span></div><div class="stat"><strong>${s.leaves}</strong><span>Leave shifts</span></div><div class="stat"><strong>${s.absent}</strong><span>Absent shifts</span></div></div></div>`}).join("")}<div class="calendar-wrap"><div class="calendar"><div class="day">Worker / day</div>${dayNames.map(d=>`<div class="day">${d}</div>`).join("")}${state.workers.filter(w=>w.active).map(w=>`<div class="worker-label">${esc(w.name)}</div>${Array.from({length:7},(_,i)=>{const d=new Date(year,month-1,1+i);if(i>=days)return `<div class="cell"></div>`;const a=attendanceFor(w.id,iso(d));const m=a?.morning,e=a?.evening;const cls=(m==='present'||e==='present')?'present':(m==='leave'||e==='leave')?'leave':(m==='absent'||e==='absent')?'absent':'';return `<div class="cell ${cls}"><div>${i+1}</div><span>${m==='present'||e==='present'?'✓':m==='leave'||e==='leave'?'L':m==='absent'||e==='absent'?'A':'·'}</span></div>`}).join("")}`).join("")}</div></div>`}
function reportPeriod(kind,refDate=new Date()){const d=new Date(refDate);if(kind==='week'){const day=d.getDay(),start=new Date(d);start.setDate(d.getDate()-day);start.setHours(0,0,0,0);const end=new Date(start);end.setDate(start.getDate()+6);end.setHours(23,59,59,999);return {start:iso(start),end:iso(end),label:`Week ${iso(start)} → ${iso(end)}`}}const start=new Date(d.getFullYear(),d.getMonth(),1),end=new Date(d.getFullYear(),d.getMonth()+1,0);return {start:iso(start),end:iso(end),label:start.toLocaleDateString(undefined,{month:"long",year:"numeric"})}}
function calculateReport(start,end){return state.workers.filter(w=>w.active).map(w=>{const rows=state.attendance.filter(a=>a.workerId===w.id&&a.date>=start&&a.date<=end);const shifts=rows.reduce((x,a)=>x+(a.morning==='present'?1:0)+(a.evening==='present'?1:0),0),leaves=rows.reduce((x,a)=>x+(a.morning==='leave'?1:0)+(a.evening==='leave'?1:0),0),absent=rows.reduce((x,a)=>x+(a.morning==='absent'?1:0)+(a.evening==='absent'?1:0),0);const paidLeave=Math.min(leaves,w.monthlyPaidLeaves*2),unpaid=Math.max(0,leaves-paidLeave);let base=w.dailyRate*(((new Date(end)-new Date(start))/86400000)+1);let deduction=w.paymentPolicy==='deduct'?unpaid*(w.dailyRate/2):0;return {workerId:w.id,name:w.name,role:w.role,presentShifts:shifts,leaveShifts:leaves,absentShifts:absent,paidLeaveShifts:paidLeave,unpaidLeaveShifts:unpaid,basePayment:base,deduction,finalPayment:Math.max(0,base-deduction)}})}
function renderReports(){const p=$("#reportsPanel"),weeks=state.reports.filter(r=>r.kind==='week').slice(0,4),months=state.reports.filter(r=>r.kind==='month").slice(0,12);p.innerHTML=`<div class="section-head"><div><h2>Reports</h2><div class="subtle">Reports are generated when the app opens and a period is due.</div></div></div><button class="mini-action" data-action="generate-report">Generate current report</button><h3>Weekly · Sunday to Saturday</h3>${weeks.length?weeks.map(reportCard).join(""):emptyReport("No weekly reports yet") }<h3>Monthly</h3>${months.length?months.map(reportCard).join(""):emptyReport("No monthly reports yet")}`}
function emptyReport(t){return `<div class="report-card"><p class="subtle">${t}</p></div>`}
function reportCard(r){return `<article class="report-card"><h3>${esc(r.label)}</h3><div class="subtle">Generated ${r.generatedAt?.toDate?r.generatedAt.toDate().toLocaleString():""}</div><div class="report-grid">${(r.summary||[]).map(x=>`<div class="report-metric"><strong>${esc(x.name)}</strong><span>${x.presentShifts} present · ${x.leaveShifts} leave · ₹${Number(x.finalPayment||0).toLocaleString("en-IN")}</span></div>`).join("")}</div></article>`}
function renderWorkers(){const p=$("#workersPanel");p.innerHTML=`<div class="section-head"><div><h2>Workers</h2><div class="subtle">Each worker can have different leave and payment rules.</div></div><button class="mini-action" data-action="add-worker">+ Worker</button></div>${state.workers.map(w=>`<article class="worker-card"><div><p class="worker-name">${esc(w.name)} ${w.active?'':'· inactive'}</p><div class="worker-meta">${esc(w.role||"Worker")} · ${w.monthlyPaidLeaves} paid leave days/month · ₹${Number(w.dailyRate||0).toLocaleString("en-IN")}/day</div></div><button class="mini-action" data-action="worker" data-id="${w.id}">Edit</button></article>`).join("")}`}
function render(){renderToday();renderMonth();renderReports();renderWorkers();$$('.tab').forEach(b=>b.classList.toggle('active',b.dataset.view===state.activeView));['today','month','reports','workers'].forEach(v=>$("#"+v+"Panel").classList.toggle('hidden',v!==state.activeView))}
function openWorkerModal(id=null){const w=id?state.workers.find(x=>x.id===id):null;$("#modalContent").innerHTML=`<h2>${w?'Edit worker':'Add worker'}</h2><p class="subtle">These settings control attendance and payment calculations.</p><form id="workerForm" class="form-grid"><label>Name<input name="name" required value="${esc(w?.name||"")}" /></label><label>Role<input name="role" value="${esc(w?.role||"")}" placeholder="Housemaid, car cleaner…" /></label><label>Paid leave allowance (days/month)<input name="monthlyPaidLeaves" type="number" min="0" step="1" value="${w?.monthlyPaidLeaves??2}" /></label><label>Daily rate (₹)<input name="dailyRate" type="number" min="0" step="1" value="${w?.dailyRate??0}" /></label><label>When paid leave is exceeded<select name="paymentPolicy"><option value="deduct" ${w?.paymentPolicy==='deduct'?'selected':''}>Deduct unpaid leave from final payment</option><option value="full" ${w?.paymentPolicy==='full'?'selected':''}>Pay full amount anyway</option></select></label><div class="form-actions"><button type="button" class="secondary-btn" id="cancelWorker">Cancel</button><button class="primary-btn">Save worker</button></div></form>`;$("#modal").classList.remove("hidden");$("#cancelWorker").onclick=()=>$("#modal").classList.add("hidden");$("#workerForm").onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),data={name:String(f.get('name')).trim(),role:String(f.get('role')).trim(),monthlyPaidLeaves:Number(f.get('monthlyPaidLeaves')),dailyRate:Number(f.get('dailyRate')),paymentPolicy:f.get('paymentPolicy'),active:w?.active!==false,updatedAt:serverTimestamp()};try{if(w)await updateDoc(doc(db,"households",state.user.uid,"workers",w.id),data);else await addDoc(workersRef(),{...data,createdAt:serverTimestamp()});$("#modal").classList.add("hidden");await loadData();toast("Worker saved")}catch(err){showError("Worker wasn't saved",err.message)}}}
async function generateReport(kind){const period=reportPeriod(kind,new Date()),summary=calculateReport(period.start,period.end),id=`${kind}_${period.start}`;try{await setDoc(doc(db,"households",state.user.uid,"reports",id),{kind,periodStart:period.start,periodEnd:period.end,label:period.label,summary,generatedAt:serverTimestamp()},{merge:true});await loadData();toast(`${kind==='week'?'Weekly':'Monthly'} report saved`)}catch(e){showError("Report couldn't be saved",e.message)}}
async function checkDueReports(){const now=new Date(),lastDay=new Date(now.getFullYear(),now.getMonth()+1,0).getDate();if(now.getDay()===6&&now.getHours()>=9)await generateReport('week');if(now.getDate()===lastDay&&now.getHours()>=21)await generateReport('month');}
function reminderKey(){return `attendanceReminder_${today()}`}
function setupReminders(){if(!('Notification'in window))return;const ask=()=>Notification.requestPermission().catch(()=>{});document.addEventListener('click',()=>{if(Notification.permission==='default')ask()},{once:true});const notify=()=>{const h=new Date().getHours(),m=new Date().getMinutes();if((h===10&&m===30)||(h===21&&m===0)){const key=reminderKey()+`_${h}`;if(!localStorage.getItem(key)){new Notification('Household attendance',{body:'Remember to mark today’s attendance.'});localStorage.setItem(key,'1')}}};setInterval(notify,30000)}
$("#googleSignInBtn").onclick=async()=>{try{await signInWithPopup(auth,provider)}catch(e){showError("Google sign-in failed",e.message)}};
$("#refreshBtn").onclick=loadData;
$("#closeModal").onclick=()=>$("#modal").classList.add("hidden");
$("#modal").onclick=e=>{if(e.target.id==='modal')$("#modal").classList.add("hidden")};
document.addEventListener('click',e=>{const tab=e.target.closest('.tab');if(tab){state.activeView=tab.dataset.view;render();return}const shift=e.target.closest('[data-shift]');if(shift){const current=attendanceFor(shift.dataset.worker,today())?.[shift.dataset.shift]||'unmarked';const next=current==='unmarked'?'present':current==='present'?'absent':current==='absent'?'leave':'unmarked';markShift(shift.dataset.worker,shift.dataset.shift,next);return}const action=e.target.closest('[data-action]');if(!action)return;if(action.dataset.action==='add-worker')openWorkerModal();if(action.dataset.action==='worker')openWorkerModal(action.dataset.id);if(action.dataset.action==='generate-report')generateReport('week')});
onAuthStateChanged(auth,async user=>{state.user=user;if(!user){$("#loginView").classList.remove("hidden");$("#loadingView").classList.add("hidden");$("#mainView").classList.add("hidden");return}$("#loginView").classList.add("hidden");await loadData();setupReminders();});
