import { initializeApp } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js";
import { getAuth, GoogleAuthProvider, signInWithPopup, onAuthStateChanged } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js";
import { getFirestore, doc, getDoc, setDoc, collection, addDoc, updateDoc, query, orderBy, getDocs, serverTimestamp } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js";

const firebaseConfig={apiKey:"AIzaSyBh7-h4GxX_cYZphqIvIYVVzMjQVFLKQyE",authDomain:"chatgpt-household-attendance.firebaseapp.com",projectId:"chatgpt-household-attendance",storageBucket:"chatgpt-household-attendance.firebasestorage.app",messagingSenderId:"640078047318",appId:"1:640078047318:web:fa508fb29be6621378f3f7"};
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),provider=new GoogleAuthProvider();
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],state={user:null,workers:[],attendance:[],reports:[],view:"today"};
const iso=d=>{const x=new Date(d);return `${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,"0")}-${String(x.getDate()).padStart(2,"0")}`},today=()=>iso(new Date()),monthKey=d=>{const x=new Date(d);return `${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,"0")}`},esc=s=>String(s??"").replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const path=(name,id)=>id?doc(db,"households",state.user.uid,name,id):collection(db,"households",state.user.uid,name);
function error(t,m){$("#modalContent").innerHTML=`<h2 class="error-title">${esc(t)}</h2><p>${esc(m)}</p><button class="primary-btn" id="ok">OK</button>`;$("#modal").classList.remove("hidden");$("#ok").onclick=()=>$("#modal").classList.add("hidden")}
function toast(m){const t=$("#toast");t.textContent=m;t.classList.remove("hidden");setTimeout(()=>t.classList.add("hidden"),2400)}
async function ensureHousehold(){const r=doc(db,"households",state.user.uid),s=await getDoc(r);if(!s.exists())await setDoc(r,{ownerUid:state.user.uid,ownerEmail:state.user.email||"",name:"My Household",members:[state.user.uid],createdAt:serverTimestamp()});}
async function load(){ $("#loadingView").classList.remove("hidden");$("#mainView").classList.add("hidden");try{await ensureHousehold();const [w,a,r]=await Promise.all([getDocs(query(path("workers"),orderBy("name"))),getDocs(query(path("attendance"),orderBy("date","desc"))),getDocs(query(path("reports"),orderBy("periodStart","desc")))]);state.workers=w.docs.map(d=>({id:d.id,...d.data(),monthlyPaidLeaves:Number(d.data().monthlyPaidLeaves??2),dailyRate:Number(d.data().dailyRate??0)}));state.attendance=a.docs.map(d=>({id:d.id,...d.data()}));state.reports=r.docs.map(d=>({id:d.id,...d.data()}));render();$("#loadingView").classList.add("hidden");$("#mainView").classList.remove("hidden")}catch(e){$("#loadingView").classList.add("hidden");error("Couldn't load data",e.message||"Please check your connection.")}}
const att=(wid,date)=>state.attendance.find(x=>x.workerId===wid&&x.date===date);
async function mark(wid,shift){const a=att(wid,today()),cur=a?.[shift]||"unmarked",next=cur==="unmarked"?"present":cur==="present"?"absent":cur==="absent"?"leave":"unmarked";try{if(a)await updateDoc(path("attendance",a.id),{[shift]:next,updatedAt:serverTimestamp()});else await addDoc(path("attendance"),{workerId:wid,date:today(),morning:shift==="morning"?next:"unmarked",evening:shift==="evening"?next:"unmarked",createdAt:serverTimestamp(),updatedAt:serverTimestamp()});await load();toast("Attendance saved")}catch(e){error("Attendance wasn't saved",e.message)}}
function shift(w,s){const v=att(w.id,today())?.[s]||"unmarked";return `<button class="shift-btn ${v}" data-shift="${s}" data-worker="${w.id}">${s[0].toUpperCase()+s.slice(1)} · ${v==="unmarked"?"Mark":v[0].toUpperCase()+v.slice(1)}</button>`}
function renderToday(){const active=state.workers.filter(w=>w.active!==false),date=new Date().toLocaleDateString(undefined,{weekday:"long",day:"numeric",month:"long"});$("#todayPanel").innerHTML=`<div class="section-head"><div><h2>Today</h2><div class="subtle">${date}</div></div><button class="mini-action" data-action="add">+ Worker</button></div>${active.length?active.map(w=>`<article class="worker-card"><div><p class="worker-name">${esc(w.name)}</p><div class="worker-meta">${esc(w.role||"Worker")} · ${w.monthlyPaidLeaves} paid leave days/month</div></div><button class="mini-action" data-action="edit" data-id="${w.id}">Details</button><div class="shift-row">${shift(w,"morning")}${shift(w,"evening")}</div></article>`).join(""):"<div class='summary-card'><h3>No workers yet</h3><p class='subtle'>Add your first worker.</p><button class='primary-btn' data-action='add'>Add worker</button></div>"}`}
function stats(w){const rows=state.attendance.filter(a=>a.workerId===w.id&&a.date.startsWith(monthKey(new Date())));return{p:rows.reduce((n,a)=>n+(a.morning==="present")+(a.evening==="present"),0),l:rows.reduce((n,a)=>n+(a.morning==="leave")+(a.evening==="leave"),0),a:rows.reduce((n,a)=>n+(a.morning==="absent")+(a.evening==="absent"),0)}}
function renderMonth(){const d=new Date(),y=d.getFullYear(),m=d.getMonth(),days=new Date(y,m+1,0).getDate(),active=state.workers.filter(w=>w.active!==false);let html=`<div class="section-head"><div><h2>${d.toLocaleDateString(undefined,{month:"long",year:"numeric"})}</h2><div class="subtle">Full month status · horizontal scroll</div></div></div>`;html+=active.map(w=>{const s=stats(w);return `<div class="summary-card"><div class="section-head"><h3>${esc(w.name)}</h3></div><div class="stats"><div class="stat"><strong>${s.p}</strong><span>Present shifts</span></div><div class="stat"><strong>${s.l}</strong><span>Leave shifts</span></div><div class="stat"><strong>${s.a}</strong><span>Absent shifts</span></div></div></div>`}).join("");html+=`<div class="calendar-wrap"><div class="calendar" style="grid-template-columns:140px repeat(${days},54px)"><div class="day">Worker</div>${Array.from({length:days},(_,i)=>`<div class="day">${i+1}</div>`).join("")}${active.map(w=>`<div class="worker-label">${esc(w.name)}</div>${Array.from({length:days},(_,i)=>{const a=att(w.id,iso(new Date(y,m,i+1))),v=a?.morning||a?.evening||"",c=v==="present"?"present":v==="leave"?"leave":v==="absent"?"absent":"";return `<div class="cell ${c}">${v==="present"?"✓":v==="leave"?"L":v==="absent"?"A":"·"}</div>`}).join("")}`).join("")}</div></div>`;$("#monthPanel").innerHTML=html}
function reportPeriod(kind){const d=new Date();if(kind==="week"){const s=new Date(d);s.setDate(d.getDate()-d.getDay());const e=new Date(s);e.setDate(s.getDate()+6);return{start:iso(s),end:iso(e),label:`Week ${iso(s)} → ${iso(e)}`}}const s=new Date(d.getFullYear(),d.getMonth(),1),e=new Date(d.getFullYear(),d.getMonth()+1,0);return{start:iso(s),end:iso(e),label:s.toLocaleDateString(undefined,{month:"long",year:"numeric"})}}
function calc(start,end){return state.workers.filter(w=>w.active!==false).map(w=>{const rows=state.attendance.filter(a=>a.workerId===w.id&&a.date>=start&&a.date<=end),present=rows.reduce((n,a)=>n+(a.morning==="present")+(a.evening==="present"),0),leave=rows.reduce((n,a)=>n+(a.morning==="leave")+(a.evening==="leave"),0),absent=rows.reduce((n,a)=>n+(a.morning==="absent")+(a.evening==="absent"),0),allowed=w.monthlyPaidLeaves*2,unpaid=Math.max(0,leave-allowed),base=w.dailyRate*((new Date(end)-new Date(start))/86400000+1),deduction=w.paymentPolicy==="full"?0:unpaid*(w.dailyRate/2);return{name:w.name,presentShifts:present,leaveShifts:leave,absentShifts:absent,unpaidLeaveShifts:unpaid,finalPayment:Math.max(0,base-deduction)}})}
async function saveReport(kind){const p=reportPeriod(kind);await setDoc(path("reports",`${kind}_${p.start}`),{kind,periodStart:p.start,periodEnd:p.end,label:p.label,summary:calc(p.start,p.end),generatedAt:serverTimestamp()},{merge:true});await load()}
function renderReports(){const ws=state.reports.filter(r=>r.kind==="week").slice(0,4),ms=state.reports.filter(r=>r.kind==="month").slice(0,12),card=r=>`<article class="report-card"><h3>${esc(r.label)}</h3><div class="report-grid">${(r.summary||[]).map(x=>`<div class="report-metric"><strong>${esc(x.name)}</strong><span>${x.presentShifts} present · ${x.leaveShifts} leave · ₹${Number(x.finalPayment||0).toLocaleString("en-IN")}</span></div>`).join("")}</div></article>`;$("#reportsPanel").innerHTML=`<div class="section-head"><div><h2>Reports</h2><div class="subtle">Sunday–Saturday weekly and monthly summaries.</div></div></div><button class="mini-action" data-action="report">Generate this week</button><h3>Weekly</h3>${ws.map(card).join("")||"<div class='report-card'><p class='subtle'>No weekly reports yet.</p></div>"}<h3>Monthly</h3>${ms.map(card).join("")||"<div class='report-card'><p class='subtle'>No monthly reports yet.</p></div>"}`}
function renderWorkers(){ $("#workersPanel").innerHTML=`<div class="section-head"><div><h2>Workers</h2><div class="subtle">Different leave and payment rules per worker.</div></div><button class="mini-action" data-action="add">+ Worker</button></div>${state.workers.map(w=>`<article class="worker-card"><div><p class="worker-name">${esc(w.name)}</p><div class="worker-meta">${esc(w.role||"Worker")} · ${w.monthlyPaidLeaves} leave days · ₹${Number(w.dailyRate||0).toLocaleString("en-IN")}/day</div></div><button class="mini-action" data-action="edit" data-id="${w.id}">Edit</button></article>`).join("")}`}
function render(){renderToday();renderMonth();renderReports();renderWorkers();$$('.tab').forEach(b=>b.classList.toggle('active',b.dataset.view===state.view));["today","month","reports","workers"].forEach(v=>$("#"+v+"Panel").classList.toggle("hidden",v!==state.view))}
function workerModal(id){const w=id?state.workers.find(x=>x.id===id):null;$("#modalContent").innerHTML=`<h2>${w?"Edit worker":"Add worker"}</h2><p class="subtle">Set this worker's rules. You can change them later.</p><form id="wf" class="form-grid"><label>Name<input name="name" required value="${esc(w?.name||"")}"></label><label>Role<input name="role" value="${esc(w?.role||"")}" placeholder="Housemaid, car cleaner…"></label><label>Paid leave allowance (days/month)<input name="leave" type="number" min="0" value="${w?.monthlyPaidLeaves??2}"></label><label>Daily rate (₹)<input name="rate" type="number" min="0" value="${w?.dailyRate??0}"></label><label>If allowance is exceeded<select name="policy"><option value="deduct" ${w?.paymentPolicy!=="full"?"selected":""}>Deduct from final payment</option><option value="full" ${w?.paymentPolicy==="full"?"selected":""}>Pay full amount anyway</option></select></label><div class="form-actions"><button type="button" class="secondary-btn" id="cancel">Cancel</button><button class="primary-btn">Save</button></div></form>`;$("#modal").classList.remove("hidden");$("#cancel").onclick=()=>$("#modal").classList.add("hidden");$("#wf").onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),data={name:String(f.get("name")).trim(),role:String(f.get("role")).trim(),monthlyPaidLeaves:Number(f.get("leave")),dailyRate:Number(f.get("rate")),paymentPolicy:f.get("policy"),active:true,updatedAt:serverTimestamp()};try{if(w)await updateDoc(path("workers",w.id),data);else await addDoc(path("workers"),{...data,createdAt:serverTimestamp()});$("#modal").classList.add("hidden");await load()}catch(e){error("Worker wasn't saved",e.message)}}}
$("#googleSignInBtn").onclick=async()=>{try{await signInWithPopup(auth,provider)}catch(e){error("Google sign-in failed",e.message)}};$("#refreshBtn").onclick=load;$("#closeModal").onclick=()=>$("#modal").classList.add("hidden");
document.addEventListener("click",e=>{const t=e.target.closest(".tab");if(t){state.view=t.dataset.view;render();return}const s=e.target.closest("[data-shift]");if(s){mark(s.dataset.worker,s.dataset.shift);return}const a=e.target.closest("[data-action]");if(!a)return;if(a.dataset.action==="add")workerModal();if(a.dataset.action==="edit")workerModal(a.dataset.id);if(a.dataset.action==="report")saveReport("week").catch(e=>error("Report failed",e.message))});
onAuthStateChanged(auth,async u=>{state.user=u;if(!u){$("#loginView").classList.remove("hidden");$("#loadingView").classList.add("hidden");$("#mainView").classList.add("hidden")}else{$("#loginView").classList.add("hidden");await load()}});
