import { initializeApp } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js";
import { getAuth, onAuthStateChanged } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js";
import { getFirestore, collection, getDocs, query, orderBy } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js";

const firebaseConfig={apiKey:"AIzaSyBh7-h4GxX_cYZphqIvIYVVzMjQVFLKQyE",authDomain:"chatgpt-household-attendance.firebaseapp.com",projectId:"chatgpt-household-attendance",storageBucket:"chatgpt-household-attendance.firebasestorage.app",messagingSenderId:"640078047318",appId:"1:640078047318:web:fa508fb29be6621378f3f7"};
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app);
const $=s=>document.querySelector(s),esc=s=>String(s??"").replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c])),money=n=>`₹${Number(n||0).toLocaleString("en-IN")}`;
let user=null,workers=[],attendance=[],settlements=[],reports=[],selectedWorker="all",selectedMonth="all";
const months=()=>{const out=[];const d=new Date();for(let i=0;i<24;i++){out.push(`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}`);d.setMonth(d.getMonth()-1)}return out};
const monthLabel=k=>{const [y,m]=k.split("-").map(Number);return new Date(y,m-1,1).toLocaleDateString(undefined,{month:"long",year:"numeric"})};
const rowsFor=(w)=>attendance.filter(a=>a.workerId===w.id&&(!selectedMonth||selectedMonth==="all"||a.date.startsWith(selectedMonth)));
function calculate(w){const rows=rowsFor(w);const p=rows.reduce((n,a)=>n+(a.morning==="present")+(a.evening==="present"),0),l=rows.reduce((n,a)=>n+(a.morning==="leave")+(a.evening==="leave"),0),ab=rows.reduce((n,a)=>n+(a.morning==="absent")+(a.evening==="absent"),0);return{p:p/2,l:l/2,ab:ab/2,shifts:rows.length*2};}
async function load(){if(!user)return;const base=`households/${user.uid}`;try{const [w,a,s,r]=await Promise.all([getDocs(query(collection(db,base,"workers"),orderBy("name"))),getDocs(query(collection(db,base,"attendance"),orderBy("date","desc"))),getDocs(query(collection(db,base,"settlements"),orderBy("periodStart","desc"))),getDocs(query(collection(db,base,"reports"),orderBy("periodStart","desc")))]);workers=w.docs.map(d=>({id:d.id,...d.data()}));attendance=a.docs.map(d=>({id:d.id,...d.data()}));settlements=s.docs.map(d=>({id:d.id,...d.data()}));reports=r.docs.map(d=>({id:d.id,...d.data()}));render()}catch(e){const p=$("#historyError");if(p){p.textContent=`Couldn't load history: ${e.message}`;p.classList.remove("hidden")}}}
function settlementCard(s){const total=Number(s.totalPayable||0),ded=Number(s.totalDeduction||0),status=s.status||"unpaid";return `<article class="report-card"><div class="section-head"><div><h3>${esc(s.label||monthLabel((s.periodStart||"").slice(0,7)))}</h3><div class="subtle">Monthly settlement · ${status==="paid"?"Paid":"Not paid"}</div></div><strong>${money(total)}</strong></div><div class="report-grid">${(s.summary||[]).map(x=>`<div class="report-metric"><strong>${esc(x.name)}</strong><span>${x.presentDays??0} present · ${x.paidLeaveDays??0} paid leave · ${x.unpaidLeaveDays??0} unpaid leave · ${money(x.finalPayment)}</span></div>`).join("")}</div><div class="settlement-line"><span>Total deductions</span><strong>${money(ded)}</strong></div></article>`}
function workerCard(w){const c=calculate(w);return `<article class="summary-card"><div class="section-head"><div><h3>${esc(w.name)}</h3><div class="subtle">${esc(w.role||"Worker")}</div></div><strong>${c.p} present days</strong></div><div class="stats"><div class="stat"><strong>${c.p}</strong><span>Present</span></div><div class="stat"><strong>${c.l}</strong><span>Leave</span></div><div class="stat"><strong>${c.ab}</strong><span>Absent</span></div></div></article>`}
function reportHistory(){return reports.filter(r=>!selectedMonth||selectedMonth==="all"||String(r.periodStart||"").startsWith(selectedMonth)).slice(0,20).map(r=>`<article class="report-card"><div class="section-head"><div><h3>${esc(r.label)}</h3><div class="subtle">${r.kind==="week"?"Weekly":"Monthly"} report</div></div><strong>${money((r.summary||[]).reduce((n,x)=>n+Number(x.finalPayment||0),0))}</strong></div></article>`).join("")}
function render(){const panel=$("#historyPanel");if(!panel)return;const filtered=selectedWorker==="all"?workers:workers.filter(w=>w.id===selectedWorker);panel.innerHTML=`<div class="section-head"><div><h2>History</h2><div class="subtle">Review past attendance, reports and payments.</div></div></div><div class="history-toolbar"><label><span class="subtle">Worker</span><select id="historyWorker"><option value="all">All workers</option>${workers.map(w=>`<option value="${w.id}" ${selectedWorker===w.id?"selected":""}>${esc(w.name)}</option>`).join("")}</select></label><label><span class="subtle">Month</span><select id="historyMonth"><option value="all">All months</option>${months().map(m=>`<option value="${m}" ${selectedMonth===m?"selected":""}>${monthLabel(m)}</option>`).join("")}</select></label></div><h3>Worker history</h3>${filtered.map(workerCard).join("")||"<div class='summary-card'><p class='subtle'>No workers found.</p></div>"}<h3>Saved settlements</h3>${settlements.filter(s=>selectedMonth==="all"||String(s.periodStart||"").startsWith(selectedMonth)).slice(0,12).map(settlementCard).join("")||"<div class='report-card'><p class='subtle'>No saved settlements yet.</p></div>"}<h3>Report history</h3>${reportHistory()||"<div class='report-card'><p class='subtle'>No reports for this filter.</p></div>"}<p id="historyError" class="subtle hidden"></p>`;$("#historyWorker").onchange=e=>{selectedWorker=e.target.value;render()};$("#historyMonth").onchange=e=>{selectedMonth=e.target.value;render()}}
onAuthStateChanged(auth,u=>{user=u;if(u)load()});
document.addEventListener("click",e=>{const t=e.target.closest(".tab");if(t?.dataset.view==="history"){setTimeout(()=>{$$(".tab").forEach(b=>b.classList.toggle("active",b.dataset.view==="history"));$$(".panel").forEach(p=>p.classList.toggle("hidden",p.id!=="historyPanel"))},0)}});
const $$=s=>[...document.querySelectorAll(s)];
