import { initializeApp } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js";
import { getAuth, onAuthStateChanged } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js";
import { getFirestore, collection, doc, getDoc, getDocs, query, where, orderBy } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js";
const firebaseConfig={apiKey:"AIzaSyBh7-h4GxX_cYZphqIvIYVVzMjQVFLKQy",authDomain:"chatgpt-household-attendance.firebaseapp.com",projectId:"chatgpt-household-attendance",storageBucket:"chatgpt-household-attendance.firebasestorage.app",messagingSenderId:"640078047318",appId:"1:640078047318:web:fa508fb29be6621378f3f7"};
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),$=s=>document.querySelector(s),esc=s=>String(s??"").replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const money=n=>`₹${Number(n||0).toLocaleString("en-IN")}`;let user=null,householdId=null,workers=[],attendance=[],settlements=[],reports=[],selectedWorker="all",selectedMonth="all";
const months=()=>{const out=[],d=new Date();for(let i=0;i<24;i++){out.push(`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}`);d.setMonth(d.getMonth()-1)}return out};const monthLabel=k=>{const[y,m]=k.split("-").map(Number);return new Date(y,m-1,1).toLocaleDateString(undefined,{month:"long",year:"numeric"})};const normEmail=e=>String(e||"").trim().toLowerCase();
async function resolveHouseholdId(){if(!user)return null;const own=await getDoc(doc(db,"households",user.uid));if(own.exists())return own.id;const email=normEmail(user.email);if(!email)return null;const q=await getDocs(query(collection(db,"households"),where("memberEmails","array-contains",email)));return q.empty?null:q.docs[0].id}
const rowsFor=w=>attendance.filter(a=>a.workerId===w.id&&(!selectedMonth||selectedMonth==="all"||a.date.startsWith(selectedMonth)));
function calculate(w){const rows=rowsFor(w),single=(w.shiftType??"double")==="single",p=rows.reduce((n,a)=>n+(a.morning==="present")+(single?0:a.evening==="present"),0),l=rows.reduce((n,a)=>n+(a.morning==="leave")+(single?0:a.evening==="leave"),0),ab=rows.reduce((n,a)=>n+(a.morning==="absent")+(single?0:a.evening==="absent"),0),divisor=single?1:2;return{p:p/divisor,l:l/divisor,ab:ab/divisor,shiftType:single?"single":"double"}}
async function load(){if(!user)return;try{householdId=householdId||await resolveHouseholdId();if(!householdId)throw new Error("No household access found for this Google account.");const base=`households/${householdId}`,[w,a,s,r]=await Promise.all([getDocs(query(collection(db,base,"workers"),orderBy("name"))),getDocs(query(collection(db,base,"attendance"),orderBy("date","desc"))),getDocs(query(collection(db,base,"settlements"),orderBy("periodStart","desc"))),getDocs(query(collection(db,base,"reports"),orderBy("periodStart","desc")))]);workers=w.docs.map(d=>({id:d.id,...d.data(),shiftType:d.data().shiftType??"double"}));attendance=a.docs.map(d=>({id:d.id,...d.data()}));settlements=s.docs.map(d=>({id:d.id,...d.data()}));reports=r.docs.map(d=>({id:d.id,...d.data()}));render()}catch(e){const p=$("#historyError");if(p){p.textContent=`Couldn't load history: ${e.message}`;p.classList.remove("hidden")}}}
function settlementCard(s){const total=Number(s.totalPayable||0),ded=Number(s.totalDeduction||0),status=s.status||"unpaid";return `<article class="report-card"><div class="section-head"><div><h3>${esc(s.label||"")}</h3><div class="subtle">Monthly settlement · ${status==="paid"?"Paid":"Not paid"}</div></div><strong>${money(total)}</strong></div><div class="report-grid">${(s.summary||[]).map(x=>`<div class="report-metric"><strong>${esc(x.name)}</strong><span>${x.presentDays??0} attended days · ${x.paidLeaveDays??0} paid leave · ${x.unpaidLeaveDays??0} unpaid leave · ${money(x.finalPayment)}</span></div>`).join("")}</div><div class="settlement-line"><span>Total deductions</span><strong>${money(ded)}</strong></div></article>`}
function workerCard(w){const c=calculate(w);return `<article class="summary-card"><div class="section-head"><div><h3>${esc(w.name)}</h3><div class="subtle">${esc(w.role||"Worker")} · ${c.shiftType==="single"?"Single shift":"Double shift"}</div></div><strong>${c.p} attended days</strong></div><div class="stats"><div class="stat"><strong>${c.p}</strong><span>Attended</span></div><div class="stat"><strong>${c.l}</strong><span>Leave</span></div><div class="stat"><strong>${c.ab}</strong><span>Absent</span></div></div></article>`}
function reportHistory(){return reports.filter(r=>!selectedMonth||selectedMonth==="all"||String(r.periodStart||"").startsWith(selectedMonth)).slice(0,20).map(r=>`<article class="report-card"><div class="section-head"><div><h3>${esc(r.label)}</h3><div class="subtle">${r.kind==="week"?"Weekly":"Monthly"} report</div></div><strong>${money((r.summary||[]).reduce((n,x)=>n+Number(x.finalPayment||0),0))}</strong></div></article>`).join("")}
function render(){const panel=$("#historyPanel");if(!panel)return;const filtered=selectedWorker==="all"?workers:workers.filter(w=>w.id===selectedWorker);panel.innerHTML=`<div class="section-head"><div><h2>History</h2><div class="subtle">Review past attendance, reports and payments.</div></div></div><div class="history-toolbar"><label><span class="subtle">Worker</span><select id="historyWorker"><option value="all">All workers</option>${workers.map(w=>`<option value="${w.id}" ${selectedWorker===w.id?"selected":""}>${esc(w.name)}</option>`).join("")}</select></label><label><span class="subtle">Month</span><select id="historyMonth"><option value="all">All months</option>${months().map(m=>`<option value="${m}" ${selectedMonth===m?"selected":""}>${monthLabel(m)}</option>`).join("")}</select></label></div><h3>Worker history</h3>${filtered.map(workerCard).join("")||"<div class='summary-card'><p class='subtle'>No workers found.</p></div>"}<h3>Saved settlements</h3>${settlements.filter(s=>selectedMonth==="all"||String(s.periodStart||"").startsWith(selectedMonth)).slice(0,12).map(settlementCard).join("")||"<div class='report-card'><p class='subtle'>No saved settlements yet.</p></div>"}<h3>Report history</h3>${reportHistory()||"<div class='report-card'><p class='subtle'>No reports for this filter.</p></div>"}<p id="historyError" class="subtle hidden"></p>`;$("#historyWorker").onchange=e=>{selectedWorker=e.target.value;render()};$("#historyMonth").onchange=e=>{selectedMonth=e.target.value;render()}}
onAuthStateChanged(auth,u=>{user=u;if(u)load()});
